platform: linux
image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: '1.31'
inputs:
- name: code-repo
outputs:
- name: versioned-manifests
run:
  path: code-repo/ci/tasks/scripts/set-image-tag
