platform: linux
image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: '1.31'
inputs:
- name: code-repo
outputs:
- name: versioned-manifests
run:
  path: ash
  args:
  - "-c"
  - 'sed "s/__IMAGE_TAG__/$(cat code-repo/.git/short_ref)/g" code-repo/deploy/deployment.yaml > versioned-manifests/deployment.yaml'