apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-rest-example
  name: spring-boot-rest-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-rest-example
  template:
    metadata:
      labels:
        app: spring-boot-rest-example
    spec:
      containers:
      - image: "alexbrand/spring-boot-rest-example:${IMAGE_TAG}"
        name: spring-boot-rest-example
